// This is automatically generated by CodeBind. Please do not modify it.

namespace Game.Hot
{
    public partial class TestForm
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_BBBButton;


        public UnityEngine.UI.Button BBBButton => m_BBBButton;


    }
}
